// This Source Code Form is subject to the terms of the MIT License.
// If a copy of the MIT was not distributed with this file, You can obtain one at https://opensource.org/licenses/MIT.
// Copyright (C) Leszek Pomianowski and OpenAPI Client Contributors.
// All Rights Reserved.

using System.Text;
using Microsoft.CodeAnalysis;
using OpenApi.Client.SourceGenerators.Contracts;

namespace OpenApi.Client.SourceGenerators.Genertion;

internal sealed partial class ClientGenerator(
    SourceProductionContext sourceProductionContext,
    OpenApiContract contract
)
{
    private const string DocumentPrefix = """
        // <auto-generated/>
        // Generated with Open API Client Source Generator. Created by Leszek Pomianowski and OpenAPI Client Contributors.
        #pragma warning disable
        #nullable enable
        """;

    public string Generate()
    {
        StringBuilder builder = new StringBuilder(DocumentPrefix);

        builder.AppendLine();
        builder.Append("namespace ");
        builder.AppendLine(contract.Namespace);
        builder.AppendLine("{");

        builder.AppendLine(ResultTemplate);
        builder.AppendLine();

        AppendInterface(builder);
        builder.AppendLine();

        AppendClass(builder);

        builder.AppendLine("}");

        builder.Replace("{{ContractClassName}}", contract.ClassName);
        builder.Replace("{{ContractTitle}}", contract.Title);
        builder.Replace("{{ContractAccess}}", contract.Access);

        return builder.ToString();
    }
}
