// This Source Code Form is subject to the terms of the MIT License.
// If a copy of the MIT was not distributed with this file, You can obtain one at https://opensource.org/licenses/MIT.
// Copyright (C) Leszek Pomianowski and OpenAPI Client Contributors.
// All Rights Reserved.

namespace OpenApi.Client.SourceGenerators;

internal static class OpenApiClientGenerationHelper
{
    public const string Attribute = """
        // <auto-generated/>
        // Generated with Open API Client Source Generator. Created by Leszek Pomianowski and OpenAPI Client Contributors.
        #pragma warning disable
        #nullable enable
        namespace OpenApi.Client
        {
            /// <summary>Library which API client should use at runtime.</summary>
            internal enum OpenApiClientSerialization
            {
                SystemTextJson,
                NewtonsoftJson
            }

            /// <summary>Indicates that a given class should have an Open API Client generated for it.</summary>
            /// <remarks>Generated with Open API Client Source Generator. See: <see href="https://github.com/lepoco/openapi.client"/></remarks>
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class OpenApiClientAttribute : global::System.Attribute
            {
                /// <summary>Initializes a new instance of the <see cref="OpenApiClientAttribute"/> class.</summary>
                /// <param name="specification">The specification resource name for the Open API Client.</param>
                /// <remarks>The specification is the name of the resource which is a yaml or json open api code.</remarks>
                public OpenApiClientAttribute(string specification)
                {
                    Specification = specification;
                    Serialization = OpenApiClientSerialization.SystemTextJson;
                }

                /// <summary>Initializes a new instance of the <see cref="OpenApiClientAttribute"/> class.</summary>
                /// <param name="specification">The specification resource name for the Open API Client.</param>
                /// <param name="serializationTool">A flag indicating whether to use the Service Collection for the Open API Client.</param>
                /// <remarks>The specification is the name of the resource which is a yaml or json open api code.</remarks>
                public OpenApiClientAttribute(string specification, OpenApiClientSerialization serializationTool)
                {
                    Specification = specification;
                    Serialization = serializationTool;
                }

                /// <summary>The specification URL for the Open API Client.</summary>
                public string Specification { get; }

                /// <summary>A flag indicating whether to use the Service Collection for the Open API Client.</summary>
                public OpenApiClientSerialization Serialization { get; }
            }
        }
        """;
}
